
# Site settings
title: BHB
subtitle: Big Healthy Brains
baseurl: bhb
url: https://baobablab.github.io/


# Contacts
email: edouard.duchesnay@cea.fr
author:
street_address:
city:
state: 
zip_code:
country: France
phone:

# Index
short_desc: BHB-10K dataset
long_desc: As of today, Big Healthy Brains (BHB)-10K dataset is an aggregation of 13 publicly available datasets of 3D T1 brain MRI scans of healthy controls (HC) acquired on more than 70 different scanners and comprising N=10K individuals All datasets are pre-processed uniformaly comprising VBM, Quasi-Raw, ... This study is intended to be extended in the future. Please refer to the roadmap to get an overall view of the BHB-10K evolution plan.

# Expiration in days
expiration_opportunities: 200
expiration_news: 300

# Social settings
500px_url: http://www.neurospin-wiki.org/pmwiki/Main/DirectionsToNeurospin
facebook_url: https://www.facebook.com/pages/NeuroSpin/171075046414933
github_url: https://github.com/neurospin
twitter_url: https://twitter.com/neurospin_91
youtube_url: https://www.youtube.com/CEASaclay
map_url: https://www.google.fr/maps/@48.720535,2.1467526,16z?hl=en

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown

# Collections
collections_dir: _collections
collections:

  challenges:
    output    : true
    permalink : /:collection/:path

  collaborators:
    output    : true
    permalink : /colleborators/:title/index.html

  people:
    output    : true
    permalink : /people/:title/index.html

  news:
    output    : true
    permalink : /news/:title/index.html

  biblio:
    output    : true
    permalink : /biblio/:title/index.html

  benchmarks:
    output    : true
    permalink : /research/:title/index.html

